---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbuckets.s3bucket.bigbang.dev
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: s3bucket.bigbang.dev/v1alpha1
    kind: XBucket
  resources:
    - name: bucket
      base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          deletionPolicy: Delete          
          forProvider:
            acl: private
            serverSideEncryptionConfiguration:
              rules:
                - applyServerSideEncryptionByDefault:
                    sseAlgorithm: AES256
          providerConfigRef:
            name: default
      patches:
        - fromFieldPath: "spec.parameters.bucketName"
          toFieldPath: "metadata.name"
        - fromFieldPath: "metadata.annotations.crossplane.io/external-name"
          toFieldPath: "metadata.annotations.crossplane.io/external-name"
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.locationConstraint"