apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xeksclusters.infra.bigbang.dev
spec:
  group: infra.bigbang.dev
  names:
    kind: XEKSCluster
    plural: xeksclusters
  claimNames:
    kind: EKSCluster
    plural: eksclusters
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    region:
                      type: string
                      description: The region in which to create the EKS Cluster.
                    clusterRoleArn:
                      description: ARN of the EKS Cluster Role to use when creating the EKS Cluster.
                      type: string
                    k8sVersion:
                      description: Kubernetes version
                      type: string
                      enum: ["1.21", "1.22", "1.23"]
                    subnetMatchLabels:
                      description: The labels to match to when selecting subnets to deploy the cluster into
                      type: object
                      additionalProperties: true
                  required:
                    - region
                    - clusterRoleArn
                    - k8sVersion
                    - subnetMatchLabels
              required:
                - parameters