apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xrdss.infra.bigbang.dev
spec:
  group: infra.bigbang.dev
  names:
    kind: Xrds
    plural: xrdss
  claimNames:
    kind: Rds
    plural: rdss
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    resourceName:
                      type: string
                      description: dbname      
                  required:
                    - resourceName
              required:
                - parameters