---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbucketpolicies.s3bucketpolicies.bigbang.dev
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: s3bucketpolicy.bigbang.dev/v1alpha1
    kind: XBucketPolicy
  resources:
    - name: bucketpolicy
      base:
        apiVersion: s3.aws.crossplane.io/v1alpha3
        kind: BucketPolicy
        spec:
          deletionPolicy: Delete          
          forProvider:
            bucketName:
            region: us-east-1
            policy:
              version: "2012-10-17"
              statements:
              - effect: Allow
                action:
                - s3:PutObject
                principal:
                  allowAnon: true
          providerConfigRef:
            name: default
      patches:
        - fromFieldPath: "spec.parameters.bucketName"
          toFieldPath: "metadata.name"
        - fromFieldPath: "metadata.annotations.crossplane.io/external-name"
          toFieldPath: "metadata.annotations.crossplane.io/external-name"
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"