---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbucketpolicies.s3bucketpolicy.bigbang.dev
spec:
  group: s3bucketpolicy.bigbang.dev
  names:
    kind: XBucketPolicy
    plural: xbucketpolicies
  claimNames:
    kind: BucketPolicy
    plural: bucketpolicies
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  bucketName:
                    type: string
                  region:
                    type: string
                required:
                  - bucketName
                  - region
            required:
              - parameters