apiVersion: databases.bigbang.dev/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: postgres-rds-test-composition
  namespace: crossplane-system
spec:
  parameters:
    storageGB: 10
    region: us-east-1
    dbName: postgres_rds_test
    publiclyAccessible: false
    dbInstanceClass: db.t3.medium
    dbSubnetMatchLabels:
      crossplane.io/claim-name: crossplane-eks-cluster-example
      internalName: dbsubnetgroup
  compositionSelector:
    matchLabels:
      provider: aws
  writeConnectionSecretToRef:
    name: postgres-rds-test-composition