apiVersion: infra.bigbang.dev/v1alpha1
kind: Rds
metadata:
  name: my-rds
  namespace: default
spec: 
  parameters:
    resourceName: my-enclave
  compositionSelector:
    matchLabels:
      provider: aws
